version: '3.4'

services:
  client.api:
    image: xjeunotfr59/clientapi:dev
    build:
      context: .
      dockerfile: Services/Client/Client.API/Dockerfile
    ports:
      - "5001:443"
      - "5000:80"
  magasin.api:
    image: xjeunotfr59/magasinapi:dev
    build:
      context: .
      dockerfile: Services/Magasin/Magasin.API/Dockerfile
  simulationflux.api:
    image: xjeunotfr59/simulationfluxapi:dev
    build:
      context: .
      dockerfile: Services/SimulationFlux/SimulationFlux.API/Dockerfile
